### ISSUE TITLE
Not working for Edge

### ISSUE THREAD

**Issue by MangelMaxime** [davidtme/Fable-WebGL#1]
When trying to see the demo at [http://davidtme.github.io/webgl/index.html](http://davidtme.github.io/webgl/index.html) I got this error.

```
SCRIPT5007: Unable to get property 'createBuffer' of undefined or null reference
bundle.js (1,21632)
```

**Comment by davidtme** [comment]
I haven’t even tried it in anything but Chrome.  I’ll see what I can sort out.

**Comment by MangelMaxime** [comment]
I can say that Firefox is working too.

**Comment by MangelMaxime** [comment]
Ok I find the bug under Edge. I will create a PR when the fix is ready.
